### ISSUE TITLE
Avoid dynamic fetching from Github

### ISSUE THREAD

**Issue by hsanjuan** [filecoin-project/network-info#37]
To do something like :

```js
const networkSchema = await Api.getData('https://raw.githubusercontent.com/filecoin-project/network-info/master/schemas/network.json')
```

is a horrible anti-pattern. It breaks local development, it causes an unnecessary 3rd-party dependency in what is otherwise a fully, ipfs-hosted static site and it is not obvious to figure out.

Instead, setup a regular CI or deployment system that triggers on commits to master.

I am going to address this, but I want to raise the flag so it does not happen in the future.

**Comment by orvn** [comment]
@hsanjuan I agree it's an anti-pattern in its current state, and we did discuss this as a team before implementing. Outside of the context, it may appear concerning, but some additional information may help.

### On this particular pattern:

- This was and is, a temporary state for this site
- This will eventually be refactored with external uptime monitoring data sources
- Right now, the network status is essentially hardcoded  
- Once we have some external endpoints, all uptime data would be from 3rd parties, and we'd refactor it as such
- This was implemented with absolute intention of a refactor 

### On this static site/application

- The page _is_ a static site that is continuously integrated, and builds on merges to `master`
- However, it's also behaving as an SPA (Vue)—so the latest data can be available during runtime, rather than compile time
- Our interpretation was that _network status_ is a tool that is temporally and state sensitive
- The build requires manual update, and always waiting _several minutes_ for a build to complete is not ideal, but this is the current state

So while it's strange to see the page making calls to its own Github source, _we did so to enable faster extensibility to the eventual goal of the page_, which is to be an accurate representation of network status and uptime (from the client-side, during runtime). 

Let me know if this helps contextualize it better.

**Comment by hsanjuan** [comment]
This does not quite explain. One thing is the network status or any other particular field, which you can fetch from anywhere.if you want.

The other is the fact that the full schema used, and everything that defines a network needs to be fetched from the current origin/master. There is no straightforward way of changing the schema or network information and testing the change without putting that on the own-master first. There is nothing dymanic about 90% of the network information.
