### ISSUE TITLE
Lack of data of chain.power

### ISSUE THREAD

**Issue by jancco** [filecoin-project/network-info#62]
**[Description]**:
When I use the follow link to query the data of Chain power:
`
https://stats.filecoin.io/api/datasources/proxy/1/query?db=chainstats-ntwk-mainnet&q=SELECT%20max(%22value%22)%20FROM%20%22chain.power%22%20WHERE%20time%20%3E%3D%20now()%20-%20100d%20GROUP%20BY%20time(1d)&epoch=s
`
It misses the data of most of the days (refer to the attach picture).

**[Suggestion]**:
Please help to fix it. Thanks!

![Chain-Power-By-Day](https://user-images.githubusercontent.com/7753311/100814897-ae043600-347d-11eb-8586-3f45bd275109.png)

**Comment by jancco** [comment]
@travisperson , @timelytree , @orvn , @hsanjuan , Could you help fix this issue? Thanks!

**Comment by travisperson** [comment]
The page at https://stats.filecoin.io isn't really a public api to be queried for this kind of information. Its goal is to try and provide a some information about the network for the last ~60 tipsets (30 minutes), we also only keep data for 30 days regardless which is why all the data falls off after the 8th of November.

If you need to query this information you run the stats tool yourself and keep the data around longer / backfill your own data.

https://github.com/filecoin-project/lotus/tree/master/cmd/lotus-stats
